### ISSUE TITLE
Question: [address prefix]

### ISSUE THREAD

**Issue by hientranduy** [cosmos-developer/baby#15]
### Question tags for categorization

- [ ] CLI
- [X] Cosmos - SDK
- [ ] Cosmos JS
- [ ] CosmWasm
- [ ] CosmWasm JS
- [ ] Windows Environment
- [X] Ubuntu Environment
- [ ] MacOS Environment

### Description of bugs

![image](https://user-images.githubusercontent.com/45411715/173762999-8fc8dc2f-dddc-4dae-b7d0-2b8e1c6aa000.png)

How to config prefix of address = baby like attached image ?

**Comment by nghuyenthevinh2000** [comment]
https://github.com/cosmos-developer/baby/blob/main/app/app.go#L109

**Comment by hientranduy** [comment]
It is hardcode in program @@! . Tks Vinh for this guide.
