### ISSUE TITLE
Question: Is there any docs for specifi field type .proto

### ISSUE THREAD

**Issue by GNaD13** [cosmos-developer/baby#17]
### Question tags for categorization

- [ ] CLI
- [ ] Cosmos - SDK
- [ ] Cosmos JS
- [ ] CosmWasm
- [ ] CosmWasm JS
- [ ] Windows Environment
- [ ] Ubuntu Environment
- [ ] MacOS Environment

### Description of bugs

I'm currently studying to write a proto for the claim module. While reading some example code, I saw some specific field types defined by Cosmos (For example: "cosmos.base.v1beta1.Coin"). Are there any docs for that kind of field?

**Comment by nghuyenthevinh2000** [comment]
https://buf.build/cosmos
