### ISSUE TITLE
Question: Error creating multiple accounts and allocating money to those

### ISSUE THREAD

**Issue by pysel** [cosmos-developer/baby#18]
### Question tags for categorization

- [X] CLI
- [ ] Protobuf + gRPC
- [X] Cosmos - SDK
- [ ] Cosmos JS
- [ ] CosmWasm
- [ ] CosmWasm JS
- [ ] Windows Environment
- [ ] Ubuntu Environment
- [ ] MacOS Environment

### Description of bugs

# Problem description
[homework] I am struggling with allocating money for those three accounts. I added a validator just so I do not get any errors when starting the chain and it seems fine at this point.
* What is the error?
When I am trying to send some ubaby to other accounts it just does not want to work
* What have you done?
Created three accounts, tried to send ubaby to each
# Picture
![Screenshot from 2022-07-03 11-31-33](https://user-images.githubusercontent.com/46343690/177035089-1236635b-e19d-4956-9de4-9d5e1fd53b71.png)

# Additional information that may help in debugging
Here is the code
![Screenshot (11)](https://user-images.githubusercontent.com/46343690/177035058-5c3e0e15-2412-4dba-9658-5f520340a607.png)

**Comment by nghuyenthevinh2000** [comment]
you can only create gentxs once per node
