### ISSUE TITLE
Question: Crisis Variable

### ISSUE THREAD

**Issue by pysel** [cosmos-developer/baby#19]
### Question tags for categorization

- [ ] CLI
- [ ] Protobuf + gRPC
- [X] Cosmos - SDK
- [ ] Cosmos JS
- [ ] CosmWasm
- [ ] CosmWasm JS
- [ ] Windows Environment
- [ ] Ubuntu Environment
- [ ] MacOS Environment

### Description of bugs

# Problem description
I was going through the multinode-local-tesnet script, I found a useful website with an explanation of everything in genesis file, however, I could not find an explanation of this variable "# update crisis variable to ubaby" aka crisis variable I guess. I am just trying to understand everything whats going on and trying not to blindly copy the file, so I would really love to know what crisis var is.
* What is the error?
---
* What have you done?
---
# Picture
* picture of the error
# Additional information that may help in debugging
https://hub.cosmos.network/main/resources/genesis.html#staking
the website i mentioned

**Comment by nghuyenthevinh2000** [comment]
crisis module is for halting the chain. For example, invariants check. In case of broken invariants, crisis module will halt the chain.

https://docs.cosmos.network/master/building-modules/invariants.html
