### ISSUE TITLE
Question: Problem with multiple nodes deploy on a single machine

### ISSUE THREAD

**Issue by GNaD13** [cosmos-developer/baby#9]
### Question tags for categorization

- [X] CLI
- [X] Cosmos - SDK
- [ ] Cosmos JS
- [ ] CosmWasm
- [ ] CosmWasm JS
- [ ] Windows Environment
- [ ] Ubuntu Environment
- [ ] MacOS Environment

### Description of bugs

I find that to deploy multiple nodes in a single machine, we must change the port (RPC, REST API, P2P) for every node.
The port configuration in some file ( $HOME/.baby/config/config.toml and /home/dangvhb/.baby/config/app.toml) store  in $HOME/.baby folder.
Is it right if we run multiple nodes, we need multiple .baby folders? So we can change the configuration for those files?

**Comment by nghuyenthevinh2000** [comment]
please run 

`bash scripts/multinode-local-testnet.sh`

and see for yourselves in $HOME/.baby
